### ISSUE TITLE
Console view: - No Live refreshes via :3480/console?page=devices

### ISSUE THREAD

**Issue by nodecentral** [akbooer/openLuup#28]
Hi @akbooer 

Hope all is well, 

I’ve started to use the console view a lot more, mainly for it’s look and simplicity , but I noticed it does not do any live updates compared to ALTUI, you have to do a full browser reload. Is that by design, or is mine not working?

Also if I want to go strait to the console view, rather than into ALTUI, I recall seeing something abut altering that in the guide by for the life of me I can’t find it. Is it possible to do, if so how would I do that..

Many thanks

**Comment by akbooer** [comment]
It might be better to ask this question on [https://smarthome.community](https://smarthome.community) where we could have a proper conversation.  However:

1.  By design.  It was never meant to replace AltUI (although I am investgating live updates at present.)  You don't need a "full browser reload", just click on the display menu item to refresh the screen.
2. `http://IP:3480/openLuup` or `http://IP:3480/console` will get you straight there.
